### ISSUE TITLE
Linkable Tab content

### ISSUE THREAD

**Issue by midzer** [thednp/bootstrap.native#238]
Hi all,
I think it would be a nice feature for all to have requested Tab content directly accessable via `#myTab` anchor in URL.
bsn would have to hook into page load handler and check if URL contains `location.hash` and switch to respective Tab accordingly.

I can have a look into implementation for this item if you think this feature suits to bsn.

Have a nice week
midzer

**Comment by thednp** [comment]
Such a feature could be implemented into our **Carousel** component as well, but I personally never used or found it useful in any particular case. I also didn't notice any trends to indicate a growing demand for hash linking.

IMO the user should be able to explore the page he/she was linked to, it's better than directing him to a specific paragraph on page load, because he/she might actually find something more valuable/informative on the page, especially when the page has a good typography + content hierarchy design.
