### ISSUE TITLE
Introduce TravisCI

### ISSUE THREAD

**Issue by szepeviktor** [thednp/bootstrap.native#247]
Are there plans to run syntax error checking and some linting on the code?
Maybe TravisCI?

**Comment by thednp** [comment]
I don't have the time or knowledge on this stuff, but feel free to contribute.

**Comment by szepeviktor** [comment]
@thednp Thanks.

What linter tool does your code pass? eslint? jshint?
What build step or other check would you like me to implement?

**Comment by thednp** [comment]
As this isn't my area of expertise, this has to be decided by public vote. 

I am reopening the issue with QUESTION tag, so everyone can share an idea/opinion on the matter.

**Comment by szepeviktor** [comment]
Aren't these `build*.js` the build scripts?

**Comment by thednp** [comment]
Yes they are.

**Comment by Vuurvlieg** [comment]
I don't have knowledge about this either. Maybe @szepeviktor could explain what it is and why we should make use of it?

**Comment by szepeviktor** [comment]
@Vuurvlieg On every commit or - preferably - PR you benefit:

- linter runs
- builds run
- any other checks run, e.g. static analysis

basically it like an assistant for you.

You may quickly discover syntax errors, wrong code styling, unused variables etc.

Are you interested?

**Comment by thednp** [comment]
For myself all these features are mostly useless because I triple check all components before commits, before publishing new versions and the final test is https://jshint.com/

**Comment by szepeviktor** [comment]
OK.
I thought this is a community project.

**Comment by Vuurvlieg** [comment]
Well, thats a lot of errors...

**Comment by szepeviktor** [comment]
My finding - if you want to produce enterprise-level code - is that **JSLint** leads to very robust code.

**Comment by thednp** [comment]
It would hurt the size alot and I honestly don't see why to go back to that "corporate" level code, I don't think it's superior in any way. As a matter of fact, our code uses some already minified expressions, the reason for most of those errors. 

For instance instead of doing this

`lib/V3/tooltip-native.js: line 81, col 65, Expected an assignment or function call and instead saw an expression.`

is the use of

```if (condition) { that() }```

we do

```condition && that();```

which is the minified version. takes less space and I find it elegant to use.

**Comment by midzer** [comment]
Yea, those results by given tool in bsn are more or less coding style issue things. There are other tools around, too, like `standardJS` for example.

IMO automatic checking is great way for large scale projects with many PRs of newcomers. This way, you can easily determine whether coding style (and maybe tests) pass properly. Overall in many cases it's quite an overhead just do it, because it's marketed as "professional".
