### ISSUE TITLE
carousel: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by nkriege** [thednp/bootstrap.native#267]
Using version 2.0.24 in Chrome. If I let the Carousel cycle, I periodically see the following error in the console:

```
bootstrap-native-v4.js:171 Uncaught TypeError: Cannot read property 'classList' of undefined
    at removeClass (bootstrap-native-v4.js:171)
    at Carousel.slideTo (bootstrap-native-v4.js:657)
    at bootstrap-native-v4.js:592
```

This happens when `getActiveIndex()` returns -1 in `slideTo`.

Other than this error, it is working great and continues to cycle through the carousel items.

**Comment by thednp** [comment]
You have a test site?

**Comment by nkriege** [comment]
The bug happens in the photo carousel on https://freshchalk.com/. The error is thrown sometimes when we wrap around from the last item in the carousel to the first.

**Comment by thednp** [comment]
@nkriege 

OK I tested the markup on my setup with latest code and the issue isn't there. Also interestingly the markup is pretty much valid so there might be something in the previous version and/or something in the way on your site.

Give the latest master version a try on your site and let me know how it goes.

**Comment by nkriege** [comment]
Thank you for looking into this. Here is a [codepen](https://codepen.io/nkriege/pen/aPgPWv) that shows the problem using the latest version of the code from master.

Notice that I am loading 21a0e061b3ba37f7c776514489b5ebb31bd9d0a from github via [jsdelivr]( http://cdn.jsdelivr.net/gh/thednp/bootstrap.native@21a0e061b3ba37f7c776514489b5ebb31bd9d0af/dist/bootstrap-native-v4.js). If I let the carousel cycle, I see this error in the console:

```
bootstrap-native-v4.js:175 Uncaught TypeError: Cannot read property 'classList' of undefined
    at removeClass (bootstrap-native-v4.js:175)
    at Carousel.slideTo (bootstrap-native-v4.js:664)
    at bootstrap-native-v4.js:599
```

**Comment by thednp** [comment]
OK I've isolated the issue, here's what I found:
* if you have the DATA API specific attributes like `data-ride="carousel"` and the proper markup, you don't need to re-init via JavaScript, here's where the issue comes into play, I removed the JS init and no more issue, so here's where I need to investigate further
* you should only use JS init for later added carousels or you simply want to re-init for using different options values
* consider using an interval of at least 5000 milliseconds, some browsers simply don't want to sync
* this far I can say it's a user issue, but I will see what I can do on to also make it work in re-init

**Comment by thednp** [comment]
OK so in conclusion this is a user issue, nothing to do with our code validity, I've isolated the exact causes.

Here are some important notices:
* don't forget the `slide` class added to your carousel, instead of `<div class="carousel carousel-fade">` use `<div class="carousel slide carousel-fade">`
* by default the carousel MUST have an active item on load, also it should be the first, to make sure we're consistent with content hierarchy and probably your content strategy
* your CSS additions break the animation flow and/or internal functionality

Check [my updated example](https://codepen.io/thednp/pen/GPVZyz) to make sure all goes well for your site.

**Comment by nkriege** [comment]
Thank you @thednp! That was very helpful. I have confirmed that removing either the `data-ride="carousel"` or the redundant javascript re-init fixes the issue.
