### ISSUE TITLE
Importing bootstrap.native with rollup

### ISSUE THREAD

**Issue by blackstormx** [thednp/bootstrap.native#309]
How do I import bootstrap.native with rollup?

Currently I am writing: 

`import { Modal } from "bootstrap.native/dist/bootstrap-native";`

But when building I get:

`Error: 'Modal' is not exported by node_modules\bootstrap.native\dist\bootstrap-native.js`
error.

**Comment by thednp** [comment]
Our components cannot be imported individually, but the entire library as a module, that would probably get fixed with the future versions based on ES6/ES7 standards.

If you look at [this wiki section](https://github.com/thednp/bootstrap.native/wiki/How-to-use#requirejs-commonjs), and I'm not experienced with rollup, but I would try something like this:

```javascript
// reference the library as dependency
var bsn = import { bootstrap-native} from "bootstrap.native/dist/bootstrap-native";

// Create a Modal instance:
var myModal = new bsn.Modal(element,options);
```

I would like other devs to confirm, but give this a try and let me know.

**Comment by blackstormx** [comment]
Okay, understood. Hope for future support of individual components to be implemented. 
Thank you.
