### ISSUE TITLE
Bug in Popover (container option)

### ISSUE THREAD

**Issue by mashablair** [thednp/bootstrap.native#312]
Hello, there is a bug in Popover.  It works fine with default container option (when popover is attached to <body> container by default).  But when I use 'data-container="#some_elem"', the placement is completely off.  

Here is a quick demo of the issue: 
https://codepen.io/mashablair/pen/rNNdpYy?editors=1010
When you hover over the link 'Read More', the popover gets displayed way down, on a very bottom left.  Also, when the screen is resized, the popover gets destroyed which is not the wanted behavior.  

It would be so amazing if someone could fix it!  Thank you!  Please LMK if you need any more detail about this issue.

**Comment by thednp** [comment]
@mashablair the use of `data-container` option is mostly for containers like modals and other similar situations where the container is having `position: absolute`. There is no need to use this option to target a container with `position:relative` or `position:static` However you can play with your container classes, I won't spend time on this idea and I didn't test it, but if you insist, there you go.

Also the default behavior is different with the original plugins because we don't use popper.js. Instead of constantly updating the tooltip/popover position on every resize trigger, we hide it.

**Comment by mashablair** [comment]
Hi @thednp,

Thank you for your response.  Could you please share a link with a demo where popovers are used in containers like modals?  Any example would be very helpful.  This will help me figure out which classes to use on my containers.  Thanks!

**Comment by thednp** [comment]
@mashablair yes, the very first [modal example](http://thednp.github.io/bootstrap.native/#modalExamples) in the demo.
