### ISSUE TITLE
Replace Bootstrap 4

### ISSUE THREAD

**Issue by Cristialt** [thednp/bootstrap.native#461]
First, thanks for this awesome project!

I am looking into ways to make it work for my Bootstrap 4 based project
Althought it's working for most of cases I feel something i'm not doing right

I have 

```
    "bootstrap.native": "2.0.67",
    "bootstrap.native-loader": "^2.0.0",
```

then 

```
test: /bootstrap\.native/,
use: {
    loader: 'bootstrap.native-loader',
    options: {
        only: [
            "alert", button", collapse", dropdown", "modal", "tooltip"
        ]
    }
}
```

and finally ` import 'bootstrap.native'` or `import BSN from 'bootstrap.native'`  both are fine...

Things are good in general, but i still have two questions if you could help me 

- how to make accordion work
- can i have this working with bootstrap.native@4.x.x [maybe this would also fix accordion]

Sorry, from documentation i wasn't able to get these things, maybe i missed something

Many thanks!

**Comment by thednp** [comment]
Unfortunately I've deprecated our V4 for Bootstrap 4.x series and cannot support it in any way mostly because of it's setup (package.json, eslint and other issues) and also the time contraints.

Why not use latest version? It's fully up to date in terms of Typescript, the overall setup.... it's just a minor set of markup differences between the two versions of the original Bootstrap. Also why not use better tooling like Vite?
