### ISSUE TITLE
Modal events

### ISSUE THREAD

**Issue by dgt41** [thednp/bootstrap.native#63]
Hi,
right now the modal doesn;t support the events: show.bs.modal, shown.bs.modal, hide.bs.modal and hidden.bs.modal. Would you consider adding them or accepting a PR for that?

(need them for rendering an iframe inside the modal, common practice I guess)

Regards Dimitris

**Comment by thednp** [comment]
Probably not.

**Comment by thednp** [comment]
Hey there. 

I have an idea. What about we get rid of **custom events** and add a **callback functionality** for all `bootstrap.native` scripts? This would work cross-browser and will not require `Event` polyfills.

The only downsize is the fact that it's gonna be a different functionality compared to the original jQuery based scripting.

**Comment by dgt41** [comment]
Personally I would not mind this twist, there are ways to work around it, although I think is a safer bet to not divert too much from the jQuery version.
Now about polyfills: is this a real problem? I mean there are even dedicated solutions for such things, e.g. https://github.com/Financial-Times/polyfill-service

**Comment by thednp** [comment]
The jQuery version strengthens even more the jQuery dependency for it's browser hacks, but that isn't my point. My point is that not everything Bootstrap does is the best, it's just good enough. 

The idea is to make things much more simple and actually more usable, like having a callback system with 3-4 lines saves you alot of time and load speed and actual performance. The polyfill service from Financial Times is again great but not the best. I cooked a 6k (instead of 30k) polyfill for IE9- that covers everything my scripts need, and as a result all scripts run faster. It's called [minifill](https://github.com/thednp/minifill). If I remove `Event` polyfill and reorganize my scripts, it's gonna get even better.

2 cents from me.
