### ISSUE TITLE
Modal get closed on click on any element

### ISSUE THREAD

**Issue by Bessonov** [thednp/bootstrap.native#89]
Hello thednp,

thank you and other commiters for this great library! Bootstrap's dependency on fat jQuery is a really show stopper.

I guess this line introduce an unexpected behavior in 1.0.5:
https://github.com/thednp/bootstrap.native/blob/1.0.5/lib/modal-native.js#L186

If I click on content area of a modal or on any input in modal, then modal close itself. If I swap line 186 with 185, then it seems to be working as expected.

**Comment by RyanZim** [comment]
@Bessonov If you can provide a JSFiddle or similar demonstrating the problem, that would be great.

**Comment by Bessonov** [comment]
@RyanZim 
I replaced jQuery with bootstrap.native:
https://jsfiddle.net/k9s9Ljjm/

**Comment by thednp** [comment]
@Bessonov thanks for reporting. Will be fixed ASAP.

**Comment by thednp** [comment]
https://github.com/thednp/bootstrap.native/commit/4be5a1dbec0c439c5ef55f7bd920b88e3f26ce98

**Comment by RyanZim** [comment]
@thednp `v1.0.51`? That should be `v1.0.6` to follow SemVer; `v1.0.51` > `v1.0.6`.

**Comment by thednp** [comment]
`1.0.6` tag will have some improvements I'm working on. `1.0.51` is only for the fix with Modal.

**Comment by RyanZim** [comment]
@thednp Yes, but if you publish `v1.0.51` to npm, npm users won't receive `v1.0.6` when it's published.

**Comment by thednp** [comment]
Oh, I see. Then we figure it out then.

**Comment by RyanZim** [comment]
If you need to publish this fix before you're done with your improvements, publish it as `v1.0.6`. If your improvements contain new features, publish it as `v1.1.0`, if not, publish them as `v1.0.7`.

Just follow SemVer:

- Breaking changes, bump the major and reset all the others.
- New features, bump the minor and reset the patch.
- Bug fixes, performance improvements, or anything that does not affect the public API, bump the patch.

Always bump version numbers by only one. Keep in mind, `v1.0.51` means 51 patch versions since `v1.0.0`.

**Comment by RyanZim** [comment]
Oops, didn't realize you had already published `v1.0.51` (BTW, you didn't make a github release for that, not sure if that was intentional). You'll have to make the next version `v1.0.52` or `v1.1.0`.

**Comment by thednp** [comment]
Yes Ryan.
